frontend:
  - changed-files:
    - any-glob-to-any-file: 'client/**/*'

backend:
  - changed-files:
    - any-glob-to-any-file: 'server/**/*'

documentation:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'

workflows:
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/**/*'
